# Generated by Django 2.1.3 on 2018-11-08 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20181107_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='day',
        ),
        migrations.RemoveField(
            model_name='event',
            name='notes',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_title',
            field=models.TextField(blank='Event', verbose_name='Event Title'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
