# Generated by Django 2.1.3 on 2018-11-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20181107_2116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('start_time',)},
        ),
    ]
